z: 0
r: 0.1

y1: 0.21
y2: 0.42

x1: -0.525
x2: -0.315
x3: -0.105
x4: 0.105
x5: 0.315
x6: 0.525

planning_group: 'manipulator'
base_frame: 'base_link'
camera_frame: 'camera'

dynamixel_sleep_time: 0.00001
dynamixel_step: 150

pour_angle: -1.55